Asp.net MVC web project/WebServicesAndEntityLinking/WebServicesAndEntityLinking/Controllers/RecordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceReference1;
using WebServicesAndEntityLinking.Data;
using WebServicesAndEntityLinking.Models;

namespace WebServicesAndEntityLinking.Controllers
{
    public class RecordsController : Controller
    {
        private readonly RecordContext _context;


        public RecordsController(RecordContext context)
        {
            _context = context;
        }

        // GET: Records
        public async Task<IActionResult> Index()
        {
              return _context.Record != null ? 
                          View(await _context.Record.ToListAsync()) :
                          Problem("Entity set 'RecordContext.Record'  is null.");
        }
        [HttpGet("Records/Index")]
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Record == null)
            {
                return Problem("Entity set 'MvcMovieContext.Movie'  is null.");
            }

            var records = from m in _context.Record
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                records = records.Where(s => s.Name!.Contains(searchString));
            }

            return View(await records.ToListAsync());
        }

        // GET: Records/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Record == null)
            {
                return NotFound();
            }

            var @record = await _context.Record
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@record == null)
            {
                return NotFound();
            }

            return View(@record);
        }

        // GET: Records/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Records/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,Age")] WebServicesAndEntityLinking.Models.Record @record)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@record);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@record);
        }

        // GET: Records/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Record == null)
            {
                return NotFound();
            }

            var @record = await _context.Record.FindAsync(id);
            if (@record == null)
            {
                return NotFound();
            }
            return View(@record);
        }

        // POST: Records/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Surname,Age")] WebServicesAndEntityLinking.Models.Record @record)
        {
            if (id != @record.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@record);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecordExists(@record.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@record);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteByName(string? searchString)
        {
            if (searchString == null || _context.Record == null)
            {
                return NotFound();
            }
            
            var record = await _context.Record.FirstOrDefaultAsync(r => r.Name == searchString);
            if (record == null)
            {
                return NotFound();
            }

            _context.Record.Remove(record);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Records/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Record == null)
            {
                return NotFound();
            }

            var @record = await _context.Record
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@record == null)
            {
                return NotFound();
            }

            return View(@record);
        }

        // POST: Records/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Record == null)
            {
                return Problem("Entity set 'RecordContext.Record'  is null.");
            }
            var @record = await _context.Record.FindAsync(id);
            if (@record != null)
            {
                _context.Record.Remove(@record);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecordExists(int id)
        {
          return (_context.Record?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Asp.net MVC web project/WebServicesAndEntityLinking/WebServicesAndEntityLinking/Controllers/RecordsWCFController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ServiceReference1;

namespace WebServicesAndEntityLinking.Controllers
{
    public class RecordsWCFController : Controller
    {
        Service1Client _service;
        public RecordsWCFController()
        {
            this._service = new Service1Client();
        }

        // GET: RecordsWCFController
        public async Task<IActionResult> Index()
        {
            var record = await _service.GetAllRecordAsync();

            return View(record.ToList<Record>());
        }
        [HttpGet("RecordsWCF/Index/Search")]
        public async Task<IActionResult> Index(string searchString)
        {
            var records = await _service.GetRecordAsync(searchString);
            return View(records.ToList());
        }


        // GET: RecordsWCFController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RecordsWCFController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,Age")] ServiceReference1.Record @record)
        {
            if (ModelState.IsValid)
            {
                await _service.InsertRecordAsync(@record);
                return RedirectToAction(nameof(Index));
            }
            return View(@record);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteByName(string searchString)
        {
            if (searchString == null )
            {
                return NotFound();
            }

            var record = await _service.DeleteRecordByNameAsync(searchString);
            if (!record)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
        // GET: RecordsWCFController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var @record = await _service.GetRecordByIdAsync(id);
            return View(@record);
        }

        // POST: RecordsWCFController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(int id, IFormCollection collection)
        {

            var @record = await _service.FindByIdAsync(id);
            if (@record != null)
            {
                await _service.DeleteRecordAsync(id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Asp.net MVC web project/WebServicesAndEntityLinking/WebServicesAndEntityLinking/Views/RecordsWCF/Create.cshtml
@model ServiceReference1.Record

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Record</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Asp.net MVC web project/WebServicesAndEntityLinking/WebServicesAndEntityLinking/Views/RecordsWCF/Delete.cshtml
@model ServiceReference1.Record

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Record</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Asp.net MVC web project/WebServicesAndEntityLinking/WebServicesAndEntityLinking/Views/RecordsWCF/Index.cshtml
@model IEnumerable<ServiceReference1.Record>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="RecordsWCF" asp-action="Search" method="get">
    <p>
        Name: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<form asp-controller="Records" asp-action="DeleteByName" method="post">
    <p>
        Name: <input type="text" name="SearchString" />
        <input type="submit" value="Delete" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>